export enum WalletTxn {
    TRAIN_ROBOCOCK = "Train robocock",
    CLAIM_PVE_REWARDS = "CLAIM_PVE_REWARDS",
    WIN_PVE = "WIN_PVE",
    SCHOLAR_ASSIGNMENT_FEE = "SCHOLAR_ASSIGNMENT_FEE",
    WIN_PVE_BY_SCHOLAR = "WIN_PVE_BY_SCHOLAR",
    SCHOLAR_ASSIGNMENT_FEE_RECEIVER = "SCHOLAR_ASSIGNMENT_FEE_RECEIVER",
    DEPOSIT = "DEPOSIT"
}